# Introduction to Data Formats and S3

In [32]:
import pandas as pd
import numpy as np

import boto3
import sagemaker.amazon.common as smac
from boto3.s3.transfer import TransferConfig

In [3]:
np.random.seed(5)

## Sample DataSet
### Three features x1,x2,x3 and a target variable y

In [4]:
n = 10

x1 = np.random.random_sample(n)       # n floating point numbers between 0 and 1
x2 = np.random.randint(100,200,n)     # n integers
x3 = np.random.random_sample(n) * 10  # n floating point numbers between 0 and 10
y = np.random.randint(0,2,n)          # Response variable 0 or 1  

In [5]:
y

array([0, 0, 1, 1, 1, 1, 0, 0, 0, 1])

In [6]:
df = pd.DataFrame({'x1':x1,
              'x2':x2, 
              'x3':x3,
              'y':y})

In [7]:
df

x1   x2        x3  y
0  0.221993  153  2.041547  0
1  0.870732  180  1.190954  0
2  0.206719  127  8.779031  1
3  0.918611  144  5.236753  1
4  0.488411  177  4.921360  1
5  0.611744  175  7.318711  1
6  0.765908  165  0.145808  0
7  0.518418  147  0.933630  0
8  0.296801  130  8.265542  0
9  0.187721  184  8.334927  1

In [9]:

df.to_csv('demo_file.csv',index=False)

In [33]:
config = TransferConfig(multipart_threshold=8388608, max_concurrency=10, use_threads=True)

In [34]:
s3 = boto3.client('s3')

In [35]:
s3.upload_file('demo_file.csv', 'psn-sagemaker', 'data_format/demo_file1.csv', Config=config)

In [ ]:
# Let's Try the Protobuf RecordIO Format
# We will use SageMaker SDK write_numpy_to_dense_tensor() method
# Data Types: Int32, Float32, Float64
# https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/amazon/common.py

In [36]:
ls

data_format_exploration.ipynb  demo_file_from_s3.recordio
demo_file.csv                  demo_file.recordio


In [37]:
s3.download_file('psn-sagemaker','data_format/demo_file.csv', 'demo_file_from_s31.csv')

In [39]:
! ls -lh

total 36K
-rw-rw-r-- 1 ec2-user ec2-user 20K May 20 18:21 data_format_exploration.ipynb
-rw-rw-r-- 1 ec2-user ec2-user 451 May 20 16:24 demo_file.csv
-rw-rw-r-- 1 ec2-user ec2-user 451 May 20 18:25 demo_file_from_s31.csv
-rw-rw-r-- 1 ec2-user ec2-user 680 May 20 16:33 demo_file_from_s3.recordio
-rw-rw-r-- 1 ec2-user ec2-user 680 May 20 16:32 demo_file.recordio


In [14]:
df.head()

x1   x2        x3  y
0  0.221993  153  2.041547  0
1  0.870732  180  1.190954  0
2  0.206719  127  8.779031  1
3  0.918611  144  5.236753  1
4  0.488411  177  4.921360  1

In [15]:
# X must be an array
X = df.as_matrix(columns=['x1','x2','x3'])

In [16]:
X

array([[2.21993171e-01, 1.53000000e+02, 2.04154748e+00],
       [8.70732306e-01, 1.80000000e+02, 1.19095357e+00],
       [2.06719155e-01, 1.27000000e+02, 8.77903071e+00],
       [9.18610908e-01, 1.44000000e+02, 5.23675290e+00],
       [4.88411189e-01, 1.77000000e+02, 4.92135999e+00],
       [6.11743863e-01, 1.75000000e+02, 7.31871100e+00],
       [7.65907856e-01, 1.65000000e+02, 1.45807511e-01],
       [5.18417988e-01, 1.47000000e+02, 9.33630336e-01],
       [2.96800502e-01, 1.30000000e+02, 8.26554249e+00],
       [1.87721229e-01, 1.84000000e+02, 8.33492742e+00]])

In [17]:
type(X)

numpy.ndarray

In [18]:
# Response/Target variable needs to a vector
# y must be a vector 
y = df.as_matrix(columns=['y'])

In [19]:
# it is right now a array of dimensions 10x1
y.shape

(10, 1)

In [20]:
y

array([[0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1]])

In [21]:
# Flatten to a single dimension array of 10 elements
y = y.ravel()

In [22]:
y

array([0, 0, 1, 1, 1, 1, 0, 0, 0, 1])

In [23]:
def write_recordio (filename, x, y=None):
    with open(filename, 'wb') as f:
        smac.write_numpy_to_dense_tensor(f, x, y)

In [24]:
def read_recordio (filename):
    with open(filename, 'rb') as f:
        record = smac.read_records(f)
        for i, r in enumerate(record):
            print ("record: {}".format(i))
            print(r)

In [25]:
write_recordio('demo_file.recordio',X,y)

In [26]:
! ls

data_format_exploration.ipynb  demo_file.csv  demo_file.recordio


In [27]:
df.head(3)

x1   x2        x3  y
0  0.221993  153  2.041547  0
1  0.870732  180  1.190954  0
2  0.206719  127  8.779031  1

In [28]:
read_recordio('demo_file.recordio',3)

record: 0
features {
  key: "values"
  value {
    float64_tensor {
      values: 0.22199317108973948
      values: 153.0
      values: 2.0415474783059215
    }
  }
}
label {
  key: "values"
  value {
    int32_tensor {
      values: 0
    }
  }
}

record: 1
features {
  key: "values"
  value {
    float64_tensor {
      values: 0.8707323061773764
      values: 180.0
      values: 1.1909535747826039
    }
  }
}
label {
  key: "values"
  value {
    int32_tensor {
      values: 0
    }
  }
}

record: 2
features {
  key: "values"
  value {
    float64_tensor {
      values: 0.20671915533942642
      values: 127.0
      values: 8.779030712603621
    }
  }
}
label {
  key: "values"
  value {
    int32_tensor {
      values: 1
    }
  }
}

